In [5]:
import pandas as pd
import numpy as np

In [10]:
s1 = pd.Series([1,3,4,5,6,6,])
print(s1.index)
print(s1.values)

RangeIndex(start=0, stop=6, step=1)
[1 3 4 5 6 6]


In [12]:
arr1 = np.array([40,56,78,80,89])
print(arr1)
print(s1.values)
print(type(s1.values),type(arr1))

[40 56 78 80 89]
[1 3 4 5 6 6]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [13]:
fruits = ["apple","banana","orange","mango"]
quantities = [20,33,56,10]
s2 = pd.Series(quantities,index=fruits)
print(s2)

apple     20
banana    33
orange    56
mango     10
dtype: int64


In [15]:
reg_no = [23,34,90,91,92]
name = ["haidar","ali","akbar","abbas","sajid"]
s3 = pd.Series(name,index=reg_no)
print(s3)

23    haidar
34       ali
90     akbar
91     abbas
92     sajid
dtype: object


In [17]:
s4 = pd.Series([20,33,52,10],index=fruits)
s5 = pd.Series([17,13,31,32],index=fruits)
print(s4+s5)
print("Sum of S::",sum(s4))

apple     37
banana    46
orange    83
mango     42
dtype: int64
Sum of S:: 115


In [19]:
fruits = ['apple','oranges','cherries','pears']
fruit2 = ['raspberries','oranges','banana','pears']
s4 = pd.Series([20,33,52,10],index=fruits)
s5 = pd.Series([17,13,31,32],index=fruits2)
print(s4+s5)

NameError: name 'fruits2' is not defined